[package]
name = "hyperspace"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"

web-sys = { version = "0.3.76", features = ["CanvasRenderingContext2d", "HtmlCanvasElement"] }
console_error_panic_hook = "0.1"
rand = "0.8"
